/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */
 
final char _FORWARD = 'w';
final char _LEFT = 'a';
final char _BACK = 's';
final char _RIGHT = 'd';
final char _STOP = 'q';
final char _ON_LEFT = 'l';
final char _ON_RIGHT = 'r';
final char _CORRIDOR = 'y';
final char _ROOM = 'z';
final char _SCAN = 'x';
final char _COMPLETE = 'f';

public void btnLeft_click(GButton source, GEvent event) { //_CODE_:btnLeft:499964:
  com4.write(_LEFT);
} //_CODE_:btnLeft:499964:

public void btnForward_click(GButton source, GEvent event) { //_CODE_:btnForward:998305:
  com4.write(_FORWARD);
} //_CODE_:btnForward:998305:

public void btnRight_click(GButton source, GEvent event) { //_CODE_:btnRight:510388:
  com4.write(_RIGHT);
} //_CODE_:btnRight:510388:

public void btnBack_click(GButton source, GEvent event) { //_CODE_:btnBack:647442:
  com4.write(_BACK);
} //_CODE_:btnBack:647442:

public void btnStop_click(GButton source, GEvent event) { //_CODE_:btnStop:418180:
  com4.write(_STOP);
} //_CODE_:btnStop:418180:

public void btnRoom_click(GButton source, GEvent event) { //_CODE_:btnRoom:717395:
  com4.write(_ROOM);
} //_CODE_:btnRoom:717395:

public void btnCorridor_click(GButton source, GEvent event) { //_CODE_:btnCorridor:294151:
  com4.write(_CORRIDOR);
} //_CODE_:btnCorridor:294151:

public void btnScan_click(GButton source, GEvent event) { //_CODE_:btnScan:890431:
  com4.write(_SCAN);
} //_CODE_:btnScan:890431:

public void btnOnLeft_click(GButton source, GEvent event) { //_CODE_:btnOnLeft:988166:
  com4.write(_ON_LEFT);
} //_CODE_:btnOnLeft:988166:

public void btnOnRight_click(GButton source, GEvent event) { //_CODE_:btnOnRight:858732:
  com4.write(_ON_RIGHT);
} //_CODE_:btnOnRight:858732:

public void textarea2_change1(GTextArea source, GEvent event) { //_CODE_:txtOutput:948000:
  println("txtOutput - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:txtOutput:948000:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  btnLeft = new GButton(this, 91, 145, 80, 30);
  btnLeft.setText("Left");
  btnLeft.addEventHandler(this, "btnLeft_click");
  btnForward = new GButton(this, 187, 104, 80, 30);
  btnForward.setText("Forward");
  btnForward.addEventHandler(this, "btnForward_click");
  btnRight = new GButton(this, 278, 145, 80, 30);
  btnRight.setText("Right");
  btnRight.addEventHandler(this, "btnRight_click");
  btnBack = new GButton(this, 185, 188, 80, 30);
  btnBack.setText("Back");
  btnBack.addEventHandler(this, "btnBack_click");
  btnStop = new GButton(this, 186, 145, 80, 30);
  btnStop.setText("Stop");
  btnStop.addEventHandler(this, "btnStop_click");
  btnRoom = new GButton(this, 185, 265, 80, 30);
  btnRoom.setText("Identify Room");
  btnRoom.addEventHandler(this, "btnRoom_click");
  btnCorridor = new GButton(this, 184, 304, 80, 30);
  btnCorridor.setText("Identify Corridor");
  btnCorridor.addEventHandler(this, "btnCorridor_click");
  btnScan = new GButton(this, 182, 386, 80, 30);
  btnScan.setText("Scan Room");
  btnScan.addEventHandler(this, "btnScan_click");
  btnOnLeft = new GButton(this, 134, 346, 80, 30);
  btnOnLeft.setText("On Left");
  btnOnLeft.addEventHandler(this, "btnOnLeft_click");
  btnOnRight = new GButton(this, 237, 346, 80, 30);
  btnOnRight.setText("On Right");
  btnOnRight.addEventHandler(this, "btnOnRight_click");
  txtOutput = new GTextArea(this, 366, 272, 320, 179, G4P.SCROLLBARS_NONE);
  txtOutput.setOpaque(true);
  txtOutput.addEventHandler(this, "textarea2_change1");
  lblOutput = new GLabel(this, 366, 245, 80, 20);
  lblOutput.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblOutput.setText("Arduino says:");
  lblOutput.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton btnLeft; 
GButton btnForward; 
GButton btnRight; 
GButton btnBack; 
GButton btnStop; 
GButton btnRoom; 
GButton btnCorridor; 
GButton btnScan; 
GButton btnOnLeft; 
GButton btnOnRight; 
GTextArea txtOutput; 
GLabel lblOutput; 